add genznodes service
BitCannaGlobal/BCNA pull request #174
Opened 2023-05-17 00:26 UTC by Genz22

2023-05-17 08:31 UTC, RaulBernal requested changes
Please check line 316.

2023-05-17 08:31 UTC, RaulBernal commented on peers_seeds_and_services.md
> +			},
I think it should ends it `}` 
Can you take a look @Genz22 ? Thanks

2023-05-18 15:29 UTC, Genz22 commented on peers_seeds_and_services.md
> +			},
fixed

2023-05-19 07:58 UTC, RaulBernal approved these changes
Thanks a lot :)

2023-05-19 07:58 UTC, merged